- src/main/scala/akka/persistence/jdbc/common/ActorConfig.scala
- src/main/scala/akka/persistence/jdbc/extension/ScalikeExtension.scala
This adds a new `validationQuery` configuration parameter. If the `jdbc-connection` configuration doesn't have a `validationQuery` field then it is set to `null` (`ConnectionPoolSettings` would still work as expected [according to its default value](https://github.com/scalikejdbc/scalikejdbc/blob/develop/scalikejdbc-core/src/main/scala/scalikejdbc/ConnectionPoolSettings.scala#L25)).
This may solve issue #9 according to [a suggestion  by Victor Klang](https://groups.google.com/d/msg/akka-user/xRappYKjoho/3sYnCk0X9K8J). We are having this issue when using Oracle, so (for us) the solution maybe is to have a `validationQuery`config field set to `select 1 from dual`. I'm not sure if this is the solution, I'm only following Victor's suggestion. Also, I'm not sure if this same problem occurs …
> Adds ´validationQuery´ configuration parameter

- README.md
- build.sbt
- src/main/scala/akka/persistence/jdbc/snapshot/Statements.scala
- src/test/scala/akka/persistence/jdbc/snapshot/JdbcSyncSnapshotStoreSpec.scala
- src/test/scala/akka/persistence/jdbc/util/JdbcInit.scala
- test-oracle.sh
As per #9, `MERGE` statement does not work well with LOB data through JDBC if LOB value size is > than 1K (approximately). Using LOB in this case require creation of temporal LOB to store updated value etc which is cumbersome. Instead, a stored procedure approach is using to achieve the same results.
The unit test was updated accordingly to test this use case with LOB > 1K
> Fix Oracle SQL `MERGE` statement usage

- build.sbt
- src/main/scala/akka/persistence/jdbc/serialization/journal/Base64JournalConverter.scala
- src/main/scala/akka/persistence/jdbc/serialization/snapshot/Base64SnapshotConverter.scala
java.util.Base64 was only created in Java 8.  By using apache commons, this library can still be built against Java 7.
> use apache commons codec Base64 vs the java8-only java.util.Base64

- src/main/scala/akka/persistence/jdbc/snapshot/Statements.scala
- src/test/scala/akka/persistence/jdbc/snapshot/JdbcSyncSnapshotStoreSpec.scala
Some DBAs frown on stored procedures.  This change eliminates the need for the stored procedure.  
And locally some tests were failing for me because timeouts were too short.  I increased some of the timeouts in those tests.
I haven't updated the library's documents, so let me know if you want that as part of the change
> use a ParameterBinder to pass snapshot into the merge statement and get rid of the stored procedure.

- build.sbt
- src/main/scala/akka/persistence/jdbc/journal/JdbcSyncWriteJournal.scala
While debugging weird bugs in my app I traced them to akka-persistence-jdbc:
I noticed that it generates like this:
```
INSERT INTO akka.journal (persistence_id, sequence_number, marker, message, created) VALUES 
```
Scalikejdbc logs error and after that application falls into the ask-timeout mess. I went through akka sources and if I understood right, it may execute asyncWriteMessages with empty messages list. So, here is the fix.
Please, release new version including it.
> don't fail on asyncWrite with empty messages

- README.md
- src/main/scala/akka/persistence/jdbc/dao/DefaultJournalQueries.scala
- src/main/scala/akka/persistence/jdbc/dao/inmemory/InMemoryJournalStorage.scala
- src/main/scala/akka/persistence/jdbc/query/journal/scaladsl/JdbcReadJournal.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
Resolves #36 
The implementation assumes that the `offset` passed to the `eventsByTag` query will be <= to the actual event count since it'll be the starting point for the future events no matter how many were actually skipped.
This is enough for my usage and maybe as far as I can go with my very limited Akka Streams knowledge, but something better could be designed.
I restored the note about ordering in the README since it is still applicable.
> Make offset sequential on eventsByTag queries

- src/main/scala/akka/persistence/jdbc/dao/bytea/SnapshotTables.scala
- src/main/scala/akka/persistence/jdbc/dao/varchar/SnapshotTables.scala
- src/main/scala/akka/persistence/jdbc/extension/AkkaPersistenceConfig.scala
The `schemaName` setting in the configuration is currently being ignored for the snapshot table. This causes problems when using a schema other than `public` with Postgres (`ERROR: relation "snapshot" does not exist`).
> Honour the schemaName setting for the snapshot table

- build.sbt
- src/main/resources/schema/h2/h2-schema.sql
- src/main/scala/akka/persistence/jdbc/dao/bytea/journal/ByteArrayJournalDao.scala
- src/main/scala/akka/persistence/jdbc/dao/bytea/journal/JournalQueries.scala
- src/main/scala/akka/persistence/jdbc/dao/bytea/readjournal/ByteArrayReadJournalDao.scala
- src/test/resources/h2-application.conf
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalSpec.scala
- src/test/scala/akka/persistence/jdbc/query/AllPersistenceIdsTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentPersistenceIdsTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/serialization/StoreOnlySerializableMessagesTest.scala
- src/test/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStoreSpec.scala
- src/test/scala/akka/persistence/jdbc/util/DropCreate.scala
Introduces the capability to use H2 as a DB.
It adds all the tests for it (and I revamped them a bit to avoid duplication).
H2 is particularly useful for component testing without the need of having a docker container already running :)
Please check my last commit. It was kind of an experiment (using stackable traits). In my view it makes things a bit cleaner (with separation of concerns for each driver), and technically it's even (a tiny bit) more performant (negligible).
I found it interesting how in the base traits it showed that not as much inputs were needed :)
> Fix for usage with h2

- src/main/resources/schema/h2/h2-schema.sql
- src/main/resources/schema/mysql/mysql-schema.sql
- src/main/resources/schema/oracle/oracle-schema.sql
- src/main/resources/schema/postgres/postgres-schema.sql
- src/main/scala/akka/persistence/jdbc/dao/bytea/journal/ByteArrayJournalDao.scala
- src/main/scala/akka/persistence/jdbc/dao/bytea/journal/JournalQueries.scala
- src/main/scala/akka/persistence/jdbc/dao/bytea/snapshot/SnapshotQueries.scala
I recently noticed recovery time degradation with growth of journal table. One of unnecessarily slow queries I found was selection of last sequence number for both journal and snapshot.
```
selectAllJournalForPersistenceId(persistenceId).map(_.sequenceNumber).max 
```
translates into this sql:
```
select max(jour.sequence_number) from (select persistence_id, sequence_number from journal where persistence_id = 'Neighbour-10' order by sequence_number desc) jour;
```
which will become slower with growth of persisted events for given persistence_id(1+ seconds on journal with total 5 000 000 records), whereas all we need is to get last sequence_number. Simpler equivalent request is:
```
selectAllJournalForPersistenceId(persistenceId).map(_.sequenceNumber).take(1) 
```
translates into this sql: …
> Sql optimizations

- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
I could be wrong about the spec, but I noticed that eventsByPersistenceId(m, n) does not complete even when n <= the max journal sequence number. Other impls (including leveldb) do terminate.
What do you think?
> eventsByPersistenceId should terminate when toSequenceNr is reached.

- README.md
- build.sbt
- src/main/scala/akka/persistence/jdbc/dao/bytea/readjournal/ByteArrayReadJournalDao.scala
slick-extensions 3.1.0 is a proprietary library (yes, Lightbend has open sourced it, but that doesn't retroactively change the license for existing releases). Technically, any project that includes it on its classpath in production that doesn't have a Lightbend subscription is in breach of the Lightbend license.
This PR solves this problem by removing the binary dependency on the Oracle driver, allowing akka-persistence-jdbc to be used in production without being in violation of Lightbend's license.
> Removed binary dependency on slick-extensions

- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- src/main/scala/akka/persistence/jdbc/query/JournalSequenceActor.scala
- src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalQueries.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/main/scala/akka/persistence/jdbc/util/ConfigOps.scala
- src/test/resources/h2-application.conf
- src/test/resources/mysql-application.conf
- src/test/resources/oracle-application.conf
- src/test/resources/postgres-application.conf
- src/test/resources/schema/h2/h2-schema.sql
- src/test/resources/schema/mysql/mysql-schema.sql
- src/test/resources/schema/oracle/oracle-schema.sql
- src/test/resources/schema/postgres/postgres-schema.sql
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/JournalSequenceActorTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/query/dao/TestProbeReadJournalDao.scala
This is the fix for #96 
To resolve the issue I have implemented an actor (JournalSequenceActor) which is started on demand.
The responsibility of this actor is to keep track of the highest id (of the ordering column).
- Whenever gaps occur in the id sequence, the actor will query again for a configurable amount of tries (10 by default, with a default delay of 1 second).
- After the 10 (default) attempts, the actor will assume that the missing ids will never appear in the database anymore.
- When executing (current) EventsByTag queries, the JournalSequenceActor is used to retrieve the max ordering id, before querying. The actor can always respond immediately which the last known max ordering id.
Features
- No additional costs on the write side of the journal (with the footnote that I did …
> Event by tag bug

- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
- src/main/scala/akka/persistence/jdbc/journal/dao/JournalDao.scala
- src/main/scala/akka/persistence/jdbc/serialization/PersistentReprSerializer.scala
- src/main/scala/akka/persistence/jdbc/util/ConfigOps.scala
- src/main/scala/akka/persistence/jdbc/util/TrySeq.scala
- src/test/resources/postgres-application.conf
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- src/test/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalSerializerTest.scala
- src/test/scala/akka/persistence/jdbc/journal/dao/TrySeqTest.scala
Implemented batch writing over multiple persistent actors. This results in a significant performance improvement.
I added result of the JDBCJournalPerfSpec below, I also added two testcases which test persist and persistAsync using a configurable amount of actors which are concurrently writing messages.
I would actually have wanted to test with more than 100 events, but the old implementation would quickly get circuit breaker timeouts...
This pull request also includes a second change: namely that it adheres to the spec for asyncReadHighestSequenceNr, which now reads the sequence number only if the previous write has completed (similar to akka-persistence-cassandra)
```
new implementation performance test output:
PersistAsync()-ing 100 took 101 ms
PersistAsync()-ing 100 took 37 ms …
```
> Batch writes

- src/test/resources/schema/h2/h2-schema.sql
I continued trying to work with H2 and I met an error saying that table "snapshot" did not exist. So I investigate and figured out that double quotes were missing into the h2-schema.sql.
I fixed it and now it works fine.
> H2 :: Fix schema name quoting

- .sbtopts
This PR explicitly removes the default GC  (`-J-XX:-UseConcMarkSweepGC`).
It seems that some jvm versions will complain when adding G1GC, but not explicitly disabling the default GC.
I'm getting the following error:
```
Conflicting collector combinations in option list; please refer to the release notes for the combinations allowed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`
```
JVM:
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
> improved sbtopts

- src/main/scala/akka/persistence/jdbc/query/JournalSequenceActor.scala
This PR solves the case where the result of `ScheduleAssumeMaxOrderingId` could be ignored when the result from `QueryOrderingIds` is processed
(fixes #126)
> fixes for max ordering jump

- src/main/scala/akka/persistence/jdbc/snapshot/dao/SnapshotTables.scala
> Snapshot table should only define one primary key

- .travis.yml
- scripts/docker-compose.yml
The travis build was broken. Because the `wnameless/oracle-xe-11g` image no longer exists on dockerhub. I chose the most-starred oracle-xe-11g instead, which should resolve our problems.
> Changed oracle test-docker image

- README.md
- src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalQueries.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/resources/h2-application.conf
- src/test/resources/mysql-application.conf
- src/test/resources/oracle-application.conf
- src/test/resources/postgres-application.conf
- src/test/scala/akka/persistence/jdbc/SimpleSpec.scala
- src/test/scala/akka/persistence/jdbc/TestSpec.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/util/DropCreate.scala
This PR bring the fix for `currentEventsByTag` and the exclusive offsets queries that was never merged in akka24.
> currentEventsByTag fix ( #124 ) + exclusive offsets queries

- src/test/resources/logback-test.xml
- src/test/scala/akka/persistence/jdbc/TablesTestSpec.scala
- src/test/scala/akka/persistence/jdbc/TestSpec.scala
- src/test/scala/akka/persistence/jdbc/query/AllPersistenceIdsTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/JournalSequenceActorTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/serialization/StoreOnlySerializableMessagesTest.scala
Made some improvements in the tests:
- One specific oracle tests now has a longer timeout, since it occasionaly failed on travis
- Global test timeout reduced from 40 minutes to 1 minute
- Resolved deprecation warnings in tests
- Enabled logging in tests, in order to do so, many dead letter warnings had to be resolved first
> Test improvements

- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
This ensures better logging in case of issues (e.g. dead letter warnings)
> Set a name for the journal sequence actor

- src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalSerializer.scala
- src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/main/scala/akka/persistence/jdbc/serialization/PersistentReprSerializer.scala
- src/test/scala/akka/persistence/jdbc/query/dao/TestProbeReadJournalDao.scala
Fixes #76 and #93 
Note this is a breaking change in the api of JdbcReadJournalDao, it should only affect those who actually implement their own read journal.
> Dependency on JournalRow removed from readjournal

- src/main/scala/akka/persistence/jdbc/query/javadsl/JdbcReadJournal.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
Added documentation for the eventsByTag an currentEventsByTag queries.
Specifically the documentation describes the meaning of the `offset` in our plugin, it states that the streams are ordered by `offset`. And that the query is implemented using a LIKE query.
Adding this documentation fixes #82. Because this information is needed for users to be able to work around the tag substring issue as described in #82. (Now that we have documented this, we can consider this a feature instead of a bug 😉)
The actual content of the docs has been based on what is originally described in the scaladoc of the akka traits for [CurrentEventsByTagQuery](https://github.com/akka/akka/blob/master/akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/CurrentEventsByTagQuery.scala) and …
> Added scaladoc to the eventsByTag queries

- src/main/scala/akka/persistence/jdbc/query/JournalSequenceActor.scala
- src/test/scala/akka/persistence/jdbc/query/JournalSequenceActorTest.scala
This PR fixes #155
Before this fix, the journal sequence actor would build several scala `Set`s containing all ordering ids which were considered missing. In case that extreme amounts of events were missing (which can be normal if the first event does not start at 1, but instead of a very high value (millions). Then the set construction would be very inefficiënt and memory-consuming.
The solution is a wrapper type `MissingElements` which internally contains a `Seq[NumericRange[OrderingId]]`. A numericRange uses a constant amount of memory regardless of its size. Which is exactly what we need in this case.
> Journal sequence actor uses NumericRanges instead of a Set to keep track of missing elements

- src/main/scala/akka/persistence/jdbc/query/JdbcReadJournalProvider.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/resources/h2-two-read-journals-application.conf
- src/test/scala/akka/persistence/jdbc/query/MultipleReadJournalTest.scala
Ensure that the journal sequence actor name is unique when multiple read journals are used.
fixes #169
Thanks to @TimMoore for logging the issue with a good idea on how to fix this!
> Actor name should be unique in case of multiple read journals

- src/main/resources/reference.conf
- src/test/resources/h2-application.conf
- src/test/resources/h2-two-read-journals-application.conf
- src/test/resources/mysql-application.conf
- src/test/resources/oracle-application.conf
- src/test/resources/postgres-application.conf
- src/test/scala/akka/persistence/jdbc/TablesTestSpec.scala
- src/test/scala/akka/persistence/jdbc/configuration/AkkaPersistenceConfigTest.scala
fixes #177
It appears that numThread must be equal to maxConnections. This PR aligns the values which also prevents a load of warnings in the log
See slick/slick#1614 and the comments below
> Aligned numThreads and maxConnections in the config

- src/main/scala/akka/persistence/jdbc/journal/dao/JournalTables.scala
- src/main/scala/akka/persistence/jdbc/snapshot/dao/SnapshotTables.scala
The default snapshot table schema used a fixed name (`snapshot_pk`) for the primary key, which makes it impossible to have more than one snapshot table in the same schema (since they both try to create the primary key with the same name). This change makes the name based on the configured table name, so that more than one can coexist.
Thanks.
> use snapshot table name in its primary key name

- README.md
- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/main/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStore.scala
- src/main/scala/akka/persistence/jdbc/util/ConfigOps.scala
- src/main/scala/akka/persistence/jdbc/util/SlickDriver.scala
- src/main/scala/akka/persistence/jdbc/util/SlickExtension.scala
- src/test/resources/h2-shared-db-application.conf
- src/test/resources/mysql-shared-db-application.conf
- src/test/resources/oracle-shared-db-application.conf
- src/test/resources/postgres-shared-db-application.conf
- src/test/scala/akka/persistence/jdbc/SharedActorSystemTestSpec.scala
- src/test/scala/akka/persistence/jdbc/SingleActorSystemPerTestSpec.scala
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalSpec.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentPersistenceIdsTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStoreSpec.scala
This PR enables more flexibility in the database configuration.
The goals of this change are the following:
- *Backwards combatibility*: Existing configurations should work as before
- *Flexibility*: It should be possible to provide a custom provider for a database, allowing any possible configuration.
- *Single db for all journals*: It should be easy to configure one single database which is used for all journals.
> Allow for single database configuration

- src/main/scala/akka/persistence/jdbc/util/SlickDriver.scala
This PR adds back overloaded methods for `SlickDriver.forDriverName` and `SlickDriver.forConfig`. Those method got an extra param (path: String) in PR #151. 
That extra param is useless for those using JNDI lookup (eg: Lagom), so it's nice to have a variant without it and also to keep backward compatibility with previous versions.
> minor improvements on SlickDriver

- README.md
- src/main/resources/reference.conf
- Fixed a mistake in the configuration example for custom database providers
- Improved documentation on thread/connection pool sizing (specifically by removing the vague 5 * number of cores recommendation and pointing to a better resource)
> Documentation fixes

- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
Switch the JdbcReadJournal actor to be created as a system actor so it can be used with Akka Typed. The same thing had to be done in this [library](https://github.com/dnvriend/akka-persistence-inmemory/pull/54). 
I did a search of the entire code base to make sure `actorOf` isn't used anywhere else. It is used in the tests but I didn't change those since it doesn't impact users.
> Use systemActorOf to allow use with Akka Typed

- .travis.yml
- README.md
- build.sh
- project/ProjectAutoPlugin.scala
- scripts/docker-compose.yml
- scripts/launch-sqlserver.sh
- scripts/sqlserver-cli.sh
- scripts/sqlserver.yml
- src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
- src/test/resources/schema/sqlserver/sqlserver-schema.sql
- src/test/resources/sqlserver-application-with-hard-delete.conf
- src/test/resources/sqlserver-application.conf
- src/test/resources/sqlserver-shared-db-application.conf
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalSpec.scala
- src/test/scala/akka/persistence/jdbc/query/AllPersistenceIdsTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentPersistenceIdsTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/HardDeleteQueryTest.scala
- src/test/scala/akka/persistence/jdbc/query/JournalSequenceActorTest.scala
- src/test/scala/akka/persistence/jdbc/query/LogicalDeleteQueryTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/serialization/StoreOnlySerializableMessagesTest.scala
- src/test/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStoreSpec.scala
- src/test/scala/akka/persistence/jdbc/util/DropCreate.scala
Adds SQL Server schema and test updates. I created a derived SQL server [image](https://hub.docker.com/r/topaztechnology/mssql-server-linux/) that allows login and database creation on startup to facilitate testing.
Write performance was initially poor vs Postgres, but significantly improved with use of `transactionally` in  `BaseByteArrayJournalDao.writeJournalRows`
This was based on a closed PR #108, thanks to @naferx
> Add support for SQL Server

- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalSerializer.scala
- src/main/scala/akka/persistence/jdbc/journal/dao/JournalTables.scala
- src/main/scala/akka/persistence/jdbc/migraition/V4Migration.scala
- src/main/scala/akka/persistence/jdbc/snapshot/dao/SnapshotTables.scala
- src/test/resources/schema/oracle/oracle-migration-v4.sql
- src/test/scala/akka/persistence/jdbc/migration/V4MigrationSpec.scala
#199 
Fixed DDL generation for legacy and non-legacy journal/snapshot table definitions.
Rows per transaction has been made configurable.
event_manifest column has been removed as it's duplicated with ser_manifest in the journal.
> #199 WIP. Fixing DDL generation.

- .travis.yml
- build.sh
- project/ProjectAutoPlugin.scala
- scripts/docker-compose.yml
- src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
This PR includes the first commit of #207 so that the writing of journal rows always runs in a transaction regardless of which database is used.
~~It turn out that H2 needs a bit more memory, however from some of my tests, it seemed that the memory settings we try to pass in the .sbtopts file are overridden by travis. To work around this I pass the memory parameters to SBT explicitly~~
It seems that the issues we are having with h2 only occur in h2 version 1.4.197 and not in the previous version. So I downloaded h2 to 1.4.196. (many issues seem to have been reported and fixed on 197, but no release has been made yet for 9 months).
In addition I discovered another bug in our build, namely that the scala 2.11 build was actually a scala 2.12 build... This has been fixed too.
Edit: 
Somehow …
> travis settings and h2 transactionally

- src/main/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStore.scala
- src/main/scala/akka/persistence/jdbc/snapshot/dao/ByteArraySnapshotDao.scala
- src/main/scala/akka/persistence/jdbc/snapshot/dao/SnapshotDao.scala
- src/main/scala/akka/persistence/jdbc/snapshot/dao/SnapshotQueries.scala
We recently found that recovering an actor with large sized snapshots failed due to a missing limit on the query. The query as is stands returns every snapshot meeting the criteria which for us was several 10s of GBs of data.
There was an existing limit on _selectByPersistenceIdAndMaxSeqNr, but none on the other 3 similar queries where a max sequence number or timestamp are specified:
_selectByPersistenceIdAndMaxTimestamp
_selectByPersistenceIdAndMaxSequenceNr
_selectByPersistenceIdAndMaxSequenceNrAndMaxTimestamp
Since Ruud highlighted that the altered queries were also being used for deletions I've added selectOneBy versions of the existing queries to be used only by the snapshot lookups.
I've also renamed most of the query functions to have a consistence convention and make it clearer …
> Fix snapshot lookup queries and improve naming for consistency and clarity

- src/main/scala/akka/persistence/jdbc/util/InputStreamOps.scala
Use a more imperative algorithm for converting an inputstream to a bytearray, which should save a lot of memory
It seems that the old version of the code, allocated a stream Cons object (32 bits) and an interger (another 32 bits) for every byte of data read from a message or snapshot. If snapshots would be very large the memory usage would be more that 8 times the original size of the snapshot (in the best case). This algorithm should be more efficient.
Note that the code is based on an example on stackoverflow, as java 8 does not yet have a simple utility to convert an inputstream to a bytearray.
Note: this code (just like the previous version) is blocking
> Fix for oracle memory issues with large snapshots.

- .travis.yml
It seems that the tests succeed. Which I did not really expect since https://github.com/slick/slick/pull/1959 is still open.
Lets keep on running jdk 11 tests on travis, so we ensure that both java versions work fine
> Include openjdk11 in the travis builds

- project/ProjectAutoPlugin.scala
- project/plugins.sbt
- version.sbt
If I understood correctly the release we want to make this will will be version 3.5.1.
I have added and enabled MiMa to check that this release is compatible with the 3.5.0 release.
There is one incompatibility (for scala 2.11 only), which occurs because the type of a lambda changed. As this lambda is not accessible when compiling, this should not be a problem.
> Enable mima to check binary compatibility

- .travis.yml
- project/ProjectAutoPlugin.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
This improved solution closes #241
Only the configured batch size of events are fetched each time. This implementation is based on the implementation of the eventsByTag query
> events by persistenceid improvements

- src/test/resources/schema/h2/h2-schema.sql
- src/test/resources/schema/mysql/mysql-schema.sql
- src/test/resources/schema/oracle/oracle-schema.sql
- src/test/resources/schema/postgres/postgres-schema.sql
- src/test/resources/schema/sqlserver/sqlserver-schema.sql
According to [discussion here](https://github.com/dnvriend/akka-persistence-jdbc/issues/250), added `NOT NULL` constraint in test/example scripts
Merging this closes #250
> Changed deleted field to not null

- .travis.yml
Akka Persistence JDBC 4.0 will not support Scala 2.11 anymore.
> Build for Scala 2.12 and 2.13

- README.md
- project/ProjectAutoPlugin.scala
- project/plugins.sbt
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
Adapt to the home:
- update links in readme
- include Lightbend in the license
- change the organisation name to "com.lightbend.akka"
> Switch to Lightbend organisation and license

- .travis.yml
- project/Dependencies.scala
Avoid installing a version of the JDK that won't be used by the job.
> Scala 2.12.10, 2.13.1; Only install the used JDK

- .travis.yml
It turns out that travis.com requires to use the `--pro` flag for encryption.
> Update the Whitesource token (again)

- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
Make compilation with Akka 2.6 work in the scheduled Travis job.
The use of the Akka 2.6 javadsl from Scala code has some issues with type-inference. This is solved with explicit types.
See #270
> Fix compilation for Akka 2.6

- core/src/main/resources/reference.conf
- core/src/test/resources/general.conf
Allow Java serialization which is disallowed by default in Akka 2.6.
#300
> Explicitly allow Java serailisation

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
As discussed here: https://github.com/akka/akka-persistence-jdbc/issues/318
We plan to cut a release for users that can't immediately migrate to the upcoming 4.0.0 (because of schema migrations). 
This is a quick fix for the most annoying bug we have. When using sharded tags (like in Lagom), the `eventsByTag` call may return events with unrelated tags. For instance, if you search for the tag "foo1", you also get events tag "foo10". 
The workaround is to filter out any partial match, in memory. Once merged and release, this can immediately benefit existing Lagom users.
> Filter tags on the fly - workaround for #168

- README.md
* Link to the docs for the 3.5 series.
* Remove the note about the move to the Akka organisation
> Link to 3.5.x docs

- core/src/main/mima-filters/3.5.3.backwards.excludes/issue-322-messagesWithBatch.excludes
- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalDaoWithReadMessages.scala
- core/src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- core/src/test/scala/akka/persistence/jdbc/query/JournalDaoStreamMessagesMemoryTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/dao/TestProbeReadJournalDao.scala
- docs/src/main/paradox/index.md
* otherwise some DBs will load everything into memory
* used the existing implementation from JdbcReadJournal.eventsByPersistenceId,
but moved it to DAO layer so that it could be used from both
JdbcAsyncWriteJournal and JdbcReadJournal
* new config replayBatchSize
also included the test from https://github.com/akka/akka-persistence-jdbc/pull/351
References #322
> read events in batches from asyncReplayMessages, #322

- core/src/main/mima-filters/3.5.3.backwards.excludes/issue-91-ordering-offset.excludes
- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/FlowControl.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalDaoWithReadMessages.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala
- core/src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/query/javadsl/JdbcReadJournal.scala
- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- core/src/main/scala/akka/persistence/jdbc/serialization/PersistentReprSerializer.scala
- core/src/test/scala/akka/persistence/jdbc/query/CurrentEventsByPersistenceIdTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/JournalDaoStreamMessagesMemoryTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/query/dao/TestProbeReadJournalDao.scala
* to be able to correlate between eventsByPersistenceId and eventsByTag
* seqNr is anyway in the EventEnvelope
* changing signature of messages and messagesWithBatch in JournalDaoWithReadMessages
* tuple (PersistentRepr, Long) to include the ordering number
* Scaladoc clarifications of the queries
References #91
> Use ordering Offset in eventsByPersistenceId, #91

- .travis.yml
- core/src/test/scala/akka/persistence/jdbc/SimpleSpec.scala
- core/src/test/scala/akka/persistence/jdbc/TablesTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/configuration/AkkaPersistenceConfigTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/HardDeleteQueryTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/JournalSequenceActorTest.scala
- migration/src/test/scala/akka/persistence/jdbc/migration/PostgresSpec.scala
- project/Dependencies.scala
* removing support for Akka 2.5.x because we can't run persistence-tck
tests with both Akka 2.5 and 2.6 due to different ScalaTest versions
* for the 4.0.0 release we don't want to support Akka 2.5.x anyway,
users that need to stay on Akka 2.5 can use the old akka-persistence-jdbc 3.5.x
version
> Update to Akka 2.6.4 and ScalaTest 3.1.1

- .scala-steward.conf
Change Scala Steward to suggest updates just once a month.
Pin Akka libraries to 2.6 (get PRs for patch releases).
> Make Scala Steward less aggressive

- core/src/main/scala/akka/persistence/jdbc/query/javadsl/JdbcReadJournal.scala
- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
Cleaned up comment about a caveat in the eventsByTag queries which has been fixed in #329 (#168)
> Cleaned up comment about a caveat in the eventsByTag 

- core/src/test/resources/mysql-application.conf
- core/src/test/resources/mysql-shared-db-application.conf
- core/src/test/resources/oracle-application.conf
- core/src/test/resources/oracle-shared-db-application.conf
- core/src/test/resources/postgres-application.conf
- core/src/test/resources/postgres-shared-db-application.conf
- core/src/test/resources/sqlserver-application.conf
- core/src/test/resources/sqlserver-shared-db-application.conf
It seems that the CRON job is failing for quite some time. 
I saw two kind of errors, both related to variable substitution for the MySQL and Postgres. It fails consistently in CRON jobs, but I have also seen some master and PR jobs failing with that. 
It's not clear to me why this was not failing all the time. For instance, the Travis build was defining `POSTGRES_USER` to be `postgres` and `POSTGRES_PASSWORD` to be `` (for all builds). That should never work because the docker has it fixed to `docker:docker`, still we see the build pass for PRs and after merging to master.
This PR reduces the amount of lose parts. We don't need to have variable substitution, except for the DB_HOST.
> Reduce amount of config variables

- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
References #451
The write-plugin is resolved using the default actor system configuration and then doesn't support an eventual configuration provided at runtime.
The PR resolves this issue by providing the runtime plugin configuration while fetching the event adapters. If the plugin configuration is empty, or if the plugin reference is not found, it will be resolved using the config of the actor system, for retro-compatibility.
> fix(#451): provide the plugin configuration when looking for the eventAdapters

- build.sbt
- core/src/main/mima-filters/4.x.x.backwards.excludes/pr-401-highest-seq-nr.excludes
- project/ProjectAutoPlugin.scala
Use dynver to detect the previous artifact dynamically.
#401 introduced a bin-incompatible change with
```diff
-  private def _highestSequenceNrForPersistenceId(persistenceId: Rep[String]): Query[Rep[Long], Long, Seq] =
-    selectAllJournalForPersistenceId(persistenceId).map(_.sequenceNumber).take(1)
+  private def _highestSequenceNrForPersistenceId(persistenceId: Rep[String]): Rep[Option[Long]] =
+    selectAllJournalForPersistenceId(persistenceId).map(_.sequenceNumber).max
-  private def _highestMarkedSequenceNrForPersistenceId(persistenceId: Rep[String]): Query[Rep[Long], Long, Seq] =
-    selectAllJournalForPersistenceId(persistenceId).filter(_.deleted === true).map(_.sequenceNumber)
+  private def _highestMarkedSequenceNrForPersistenceId(persistenceId: Rep[String]): …
```
> MiMa: detect previous version; allow change from #401

- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/legacy/JournalQueries.scala
There is a problem with the performance of `_highestSequenceNrForPersistenceId` query (generated by slick).
It's causing a long recovery time on my dataset (~ 69 millions of records in the journal). Adding the limit changes the generated query and drastically improves performance (in my case it was reduces from seconds to milliseconds).
Previous query:
`select max(x2.x3) from (select "persistence_id" as x4, "sequence_number" as x3 from "event_journal" where "persistence_id" = '[id]' order by "sequence_number" desc) x2;`
```
Aggregate  (cost=8524.87..8524.88 rows=1 width=8)
->  Index Only Scan Backward using event_journal_pkey on event_journal  (cost=0.57..8430.38 rows=7559 width=524)
Index Cond: (persistence_id = '[id]'::text)
```
After the change:
`explain select max(x2.x3) from (select …
> Fix performance of _highestSequenceNrForPersistenceId slick query

- core/src/main/scala/akka/persistence/jdbc/testkit/internal/SchemaUtilsImpl.scala
- core/src/main/scala/akka/persistence/jdbc/testkit/javadsl/SchemaUtils.scala
- core/src/main/scala/akka/persistence/jdbc/testkit/scaladsl/SchemaUtils.scala
- core/src/test/scala/akka/persistence/jdbc/util/DropCreate.scala
> Extends SchemaUtils for custom config keys

- core/src/it/scala/akka/persistence/jdbc/integration/PostgresDurableStateStorePluginSpec.scala
- core/src/main/mima-filters/5.0.1.backwards.excludes/pr-570-akka-serialization.excludes
- core/src/main/resources/reference.conf
- core/src/main/resources/schema/postgres/postgres-create-schema-legacy.sql
- core/src/main/resources/schema/postgres/postgres-drop-schema-legacy.sql
- core/src/main/scala/akka/persistence/jdbc/state/DurableStateStoreProvider.scala
- core/src/main/scala/akka/persistence/jdbc/state/scaladsl/JdbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala
- docs/src/main/paradox/index.md
- docs/src/main/paradox/query.md
This PR adds a new constructor for `JdbcDurableStateStoreProvider` for plugin integration.
References https://github.com/akka/akka/issues/30277
> New constructor for JdbcDurableStateStoreProvider

- core/src/main/scala/akka/persistence/jdbc/state/DurableStateQueries.scala
- core/src/main/scala/akka/persistence/jdbc/state/SequenceNextValUpdater.scala
References #573 
Thanks @debasishg for pointing out the correct syntax (`#$`). TIL
PS: I've tested locally both PG and H2.
> Durable state DDL is all configurable

- core/src/test/java/akka/persistence/jdbc/JavadslSnippets.java
- core/src/test/java/akka/persistence/jdbc/state/JavadslSnippets.java
- core/src/test/scala/akka/persistence/jdbc/state/ScaladslSnippets.scala
- docs/src/main/paradox/durable-state-store.md
- project/plugins.sbt
References https://github.com/akka/akka/issues/30277
> Initial version of durable state plugin docs

- core/src/test/java/akka/persistence/jdbc/state/JavadslSnippets.java
- core/src/test/scala/akka/persistence/jdbc/state/ScaladslSnippets.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala
References https://github.com/akka/akka/issues/30277
> Use store identifier to fetch plugin class

- core/src/main/mima-filters/5.0.2.backwards.excludes/issue-585-performance-regression.excludes
- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/BaseDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/DefaultJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/legacy/ByteArrayJournalDao.scala
References #585 
`akka.persistence.jdbc.integration.PostgresJournalPerfSpec` on master against local docker postgres:
```
[info] A PersistentActor's performance
[info] - must measure: persist()-ing 100 events for 100 actors (10 seconds, 218 milliseconds)
[info]   + Persist()-ing 100 * 100 took 10184 ms
[info]   + Average time: 10184 ms
[info] A PersistentActor's performance
[info] - must measure: persistAsync()-ing 100 events for 100 actors (3 seconds, 984 milliseconds)
[info]   + persistAsync()-ing 100 * 100 took 3955 ms
[info]   + Average time: 3955 ms
```
With this fix, back to pre-5.0.0 levels:
```
[info] A PersistentActor's performance
[info] - must measure: persist()-ing 100 events for 100 actors (2 seconds, 244 milliseconds)
[info]   + Persist()-ing 100 * 100 took 2213 ms
[info] …
```
> Performance regression for events without tags

- build.sbt
We need to force mima to use 5.0.2 because 5.0.3 never got published.
> Force mima to use 5.0.2

- core/src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
References #540
I have a suspicion about the H2ScalaEventsByTagTest failures being
about journal init, but not sure. This will help pinpointing that.
> fix: fail fast in query tests if actors fail to stop 

- docs/src/main/paradox/configuration.md
Current link for SlickDatabaseProvider goes to a 404
> Correct link in documentation

- core/src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
> Mark some tests as pending for Oracle with legacy dao

- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByUnfrequentTagTest.scala
for infrequent tags because of an optimization that only works for full journal querying
Follow up to #681
> fix: The new events-by-tag-buffer-sizes-per-query could miss events

- .github/workflows/fossa.yml
- .github/workflows/link-validator.yml
- docs/src/main/paradox/migration.md
References https://github.com/akka/akka-projection/pull/730
> chore: modern Fossa installation; link checker updates

- docs/src/main/paradox/migration.md
> docs: Wrong latest version in the migration guide

- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/BaseJournalDaoWithReadMessages.scala
No References.
Reducing memory cost on replaying query stream
Additional bonus: slight performance improvement.
```bash
jmh:run -i 3 -wi 3 -f 1 .JdbcAsyncJournalBenchmark
[info] Benchmark                                     Mode  Cnt       Score       Error  Units
[info] JdbcAsyncJournalBenchmark.originalAsync      thrpt    3  590394.058 ± 38433.920  ops/s
[info] JdbcAsyncJournalBenchmark.streamWithCollect  thrpt    3  594978.499 ±  2034.776  ops/s
[info] Benchmark                                     Mode  Cnt       Score       Error  Units
[info] JdbcAsyncJournalBenchmark.originalAsync      thrpt    3  584438.653 ± 35769.421  ops/s
[info] JdbcAsyncJournalBenchmark.streamWithCollect  thrpt    3  587042.327 ± 15553.554  ops/s
```
JMH for this change: …
> perf: Reducing memory cost while replaying

- core/src/it/scala/akka/persistence/jdbc/integration/EventsByTagTest.scala
- core/src/main/scala/akka/persistence/jdbc/query/dao/legacy/ByteArrayReadJournalDao.scala
- core/src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventsByUnfrequentTagTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
References #673
This PR has been fix something like `EventsByTagTest`, but i got the ERROR on `JournalSequenceActorTest`.
I think it was my environment complaining database too slow, waiting for investigation.
> fix: Avoid using boolean types under Oracle's data type limitations #673

- CONTRIBUTING.md
- README.md
- project/plugins.sbt
Even removed references to Travis and Gitter.
References
- https://github.com/akka/akka-paradox/releases/tag/v0.53
> bump: Akka Paradox; remove old references in readmes

- docs/src/main/paradox/migration.md
> docs: event tag migration guide

- core/src/main/scala/akka/persistence/jdbc/state/DurableStateQueries.scala
- core/src/main/scala/akka/persistence/jdbc/state/SequenceNextValUpdater.scala
- integration/src/test/scala/akka/persistence/jdbc/integration/MySQLDurableStateStorePluginSpec.scala
- integration/src/test/scala/akka/persistence/jdbc/integration/MySQLScalaJdbcDurableStateChangesByTagTest.scala
> Add MySQL implementation

- project/Dependencies.scala
> chore: Pin slf4j-api to 1.7 to avoid downstream problems with Akka

- core/src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
References #782
Delay persistence to the start of the query
> fix: flaky CurrentEventsByTagTest

- project/Dependencies.scala
Fix for MySQL.
Slf4j-API bump is excluded since before.
References
- https://github.com/slick/slick/releases/tag/v3.5.1
> bump: Slick 3.5.1 (was 3.5.0)

- core/src/test/scala/akka/persistence/jdbc/query/JournalDaoStreamMessagesMemoryTest.scala
JournalDaoStreamMessagesMemoryTest didn't work in the newDao because it uses legacyDao, we could create dao instance via reflection to make it works.
> fix not working JournalDaoStreamMessagesMemoryTest

- build.sbt
- project/Dependencies.scala
Direct dependency on scala-reflect sorts it until upstream is fixed
References #824
> fix: Workaround slick dependency issue #824

- core/src/main/scala/akka/persistence/jdbc/journal/dao/DefaultJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala
- scripts/launch-all.sh
- scripts/launch-mysql.sh
- scripts/launch-oracle.sh
- scripts/launch-postgres.sh
- scripts/launch-sqlserver.sh
First delete all event but the last and then mark the last as delete.
> fix: delete all but last

- core/src/main/scala/akka/persistence/jdbc/state/scaladsl/JdbcDurableStateStore.scala
The present implementation of the durable state store treats a deserialization failure as "successful but absent" (a `Future` containing `None`)
In contrast:
* this plugin's journal and snapshot stores will fail the future (see [journal](https://github.com/akka/akka-persistence-jdbc/blob/55f38148ff5782a0d993b8f51b810f163160587e/core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala#L124) and [snapshot](https://github.com/akka/akka-persistence-jdbc/blob/55f38148ff5782a0d993b8f51b810f163160587e/core/src/main/scala/akka/persistence/jdbc/snapshot/dao/DefaultSnapshotDao.scala#L72)
* [the R2DBC plugin's durable state store will fail the future](https://github.com/akka/akka-persistence-r2dbc/blob/93246b520a9efbdfd5d6b5205f80ab99fd9108f6/core/src/main/scala/akka/persistence/ …
> fix: deserialization failure in durable state should result in failed future

- core/src/main/scala/akka/persistence/jdbc/db/SlickExtension.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/DefaultJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/snapshot/dao/DefaultSnapshotDao.scala
- core/src/main/scala/akka/persistence/jdbc/state/javadsl/JdbcDurableStateStore.scala
- core/src/main/scala/akka/persistence/jdbc/testkit/javadsl/SchemaUtils.scala
- project/Dependencies.scala
- bump akka to 2.10.0-M1 and other dependencies
- slick to not exclude slf4j anymore
- drop scala.collection.JavaConverters
- drop akka.dispatch.ExecutionContexts
- drop scala.compat.java8
> chore: bump to akka 2.10.0-M1, align with changes from upstream

- README.md
- build.sbt
- core/src/main/scala/akka/persistence/jdbc/testkit/javadsl/SchemaUtils.scala
- core/src/main/scala/akka/persistence/jdbc/testkit/scaladsl/SchemaUtils.scala
- docs/release-train-issue-template.md
- docs/src/main/paradox/snapshots.md
- project/Dependencies.scala
- project/ProjectAutoPlugin.scala
- scripts/link-validator.conf
References
- https://github.com/akka/akka/pull/32518
> docs: revise URL structure (libraries)

- project/Dependencies.scala
References
- https://github.com/slick/slick/releases/tag/v3.5.2
> bump: Slick 3.5.2 (was 3.5.1)

- CONTRIBUTING.md
- LICENSE
- README.md
- docs/release-train-issue-template.md
- project/Dependencies.scala
- project/ProjectAutoPlugin.scala
- project/plugins.sbt
- project/project-info.conf
- bump akka to 2.10.0
- license date and version
- bump sbt-paradox-akka
- remove gitter
> Pre release 24.10

- project/Dependencies.scala
as discussed in https://github.com/akka/akka-persistence-jdbc/pull/908
> fix: revert to Slick v3.5.1

- core/src/main/mima-filters/5.5.2.backwards.excludes/pr-928-cleanup-tool.excludes
- core/src/main/scala/akka/persistence/jdbc/cleanup/javadsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/jdbc/cleanup/scaladsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/DefaultJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalDaoInstantiation.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/legacy/ByteArrayJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStore.scala
- core/src/main/scala/akka/persistence/jdbc/snapshot/dao/SnapshotDaoInstantiation.scala
- core/src/test/scala/akka/persistence/jdbc/cleanup/scaladsl/EventSourcedCleanupTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- integration/src/test/scala/akka/persistence/jdbc/integration/EventSourcedCleanupTest.scala
This adds a cleanup tool, similar to akka-persistence-r2dbc.
I've kept the API really limited, only including the methods that I need for my use case.
> Added cleanup tool
