akka/akka-persistence-jdbc

- build.sbt
- src/main/scala/akka/persistence/jdbc/dao/bytea/JournalQueries.scala
- src/main/scala/akka/persistence/jdbc/dao/bytea/SnapshotQueries.scala
> Significant performance boost by using compiled queries

- build.sh
- project/plugins.sbt
- scripts/docker-compose.yml
- scripts/oracle.yml
- src/main/resources/schema/oracle/oracle-schema.sql
- src/main/scala/akka/persistence/jdbc/dao/bytea/readjournal/ByteArrayReadJournalDao.scala
- src/test/resources/docker.conf
- src/test/resources/mysql-application.conf
- src/test/resources/oracle-application.conf
- src/test/resources/postgres-application.conf
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/util/DropCreate.scala
- test.sh
Okay, finally... :-)
First of all: **Thanks for this incredible amount of effort you put into this community plugin!**
I learned so much doing these changes and really appreciate your work!
A word of warning: The MySQL Tests didn't quite work after I rebased to 2.6.3, I was always running into timeouts within the Actor tests...
Also please have an **extra extra** careful look at this PR, since I am not really sure I knew exactly what I was doing all the time and relied mostly on the existing tests... so be warned! ;-)
To summarize what I did:
- changed the bash scripts to not just delete all not running docker containers but instead use docker-compose - for people running docker natively that might have been a big surprise in the past
- added host-config for cases when not using …
> Oracle 12 c

- src/main/scala/akka/persistence/jdbc/dao/bytea/journal/JournalTables.scala
> Ensure Journal tags DDL is nullable.

- README.md
> fix misprint

- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/resources/h2-application.conf
- src/test/resources/mysql-application.conf
- src/test/resources/oracle-application.conf
- src/test/resources/postgres-application.conf
- src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
> Added support for event adapters on query side (backport of #103).

- src/main/scala/akka/persistence/jdbc/journal/dao/JournalTables.scala
#130 Remove ordering from the table primary key and creating a unique index
> Align JournalTables with the sql schemas

- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
This PR is based on previous PR from @WellingR (PR #129). 
It introduces a `FlowControl` model that replaces the double boolean logic by a three state ADT.
> Current events by tag fix wtih flow control

- src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/resources/h2-application.conf
- src/test/resources/mysql-application.conf
- src/test/resources/oracle-application.conf
- src/test/resources/postgres-application.conf
- src/test/scala/akka/persistence/jdbc/SimpleSpec.scala
- src/test/scala/akka/persistence/jdbc/TestSpec.scala
- src/test/scala/akka/persistence/jdbc/query/CurrentEventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventAdapterTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
- src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- src/test/scala/akka/persistence/jdbc/util/DropCreate.scala
This is should fix #124.
This PR is ready be merged, however in the future we might want to refactor some of the code in the JdbcReadJournal to make it easier to test.
> currentEventsByTag fix ( #124 )

- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
#152 has been merged, I have re-targeted this branch to master
fixes #149
> Efficiency improvement in eventsByTag

- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
- src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala
- src/test/scala/akka/persistence/jdbc/configuration/AkkaPersistenceConfigTest.scala
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- src/test/scala/akka/persistence/jdbc/journal/JdbcJournalSpec.scala
> Implement optional physical deletion of marked journal messages

- .travis.yml
- project/ProjectAutoPlugin.scala
> Dependency updates: Scala -> 2.12.5, Akka -> 2.5.11, Slick -> 3.2.3

- .travis.yml
- project/ProjectAutoPlugin.scala
- scala 2.12.6
- akka 2.5.16
- scalatest 3.0.5 (test only)
- postgres 42.2.5 (test only)
- mysql 8.0.12 (test only)
fixes #198
> Dependency updates

- README.md
- src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- src/main/scala/akka/persistence/jdbc/util/SlickExtension.scala
- src/test/resources/jndi-application.conf
- src/test/resources/jndi-shared-db-application.conf
- src/test/scala/akka/persistence/jdbc/SingleActorSystemPerTestSpec.scala
- src/test/scala/akka/persistence/jdbc/configuration/AkkaPersistenceConfigTest.scala
- src/test/scala/akka/persistence/jdbc/configuration/JNDIConfigTest.scala
- src/test/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStoreSpec.scala
> Added jndi config example and test

- README.md
- version.sbt
Todos:
Afterwards this PR can be merged and I will make sure the release is published (with help of dnvriend)
> WIP: preparing for 3.5.0 release

- .sbtopts
- .travis.yml
- project/ProjectAutoPlugin.scala
- project/build.properties
- scripts/docker-compose.yml
- scripts/oracle.yml
This PR also fixes the build failures on master, because the docker image we used was no longer available
> Dependency updates, use different docker image for testing

- src/test/scala/akka/persistence/jdbc/util/ClasspathResources.scala
> Removed unused test code that relied on deprecated scala xml classes

- .github/release-drafter.yml
When enabled the bot will list all merged PRs in the draft release notes.
> Build: configure release drafter

- .travis.yml
- build.sbt
- project/plugins.sbt
- version.sbt
Use Dynver to automatically derive the version.
https://github.com/dwijnand/sbt-dynver/
> Use Dynver to create version

- project/plugins.sbt
Use the latest Mima version for sbt 1.2.8 (0.6.1 reqiures sbt 1.3.x)
> Build: use Mima 0.6.0

- build.sbt
- project/Dependencies.scala
- project/ProjectAutoPlugin.scala
- project/build.properties
- project/plugins.sbt
Use sbt 1.3.4 and become more ready for a mult-project build.
> sbt 1.3.4 and more standard sbt structure

- .travis.yml
Use Travis stages so that simple checks can go first.
> Travis: use stages instead of build matrix

- .travis.yml
- build.sbt
Check code style in just one Travis step via an sbt task.
> Build: check style in one step

- RELEASING.md
- docs/release-train-issue-template.md
- scripts/create-release-issue.sh
Add instructions about all steps required to do a full release.
The instructions follow what most Akka sattellite do. They are untested so far.
> Release instructions

- build.sbt
- migration/src/main/scala/akka/persistence/jdbc/migration/Main.scala
- migration/src/main/scala/db/migration/postgres/V003__UpdateUsers.scala
- migration/src/test/scala/akka/persistence/jdbc/migration/PostgresSpec.scala
- project/plugins.sbt
This update the sbt-header plugin and add headers on files in the `migration` module. I have no idea how #298 got a green build.
> Update sbt-headers and add missing headers

- build.sbt
- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/jdbc/db/SlickDatabase.scala
- core/src/main/scala/akka/persistence/jdbc/db/SlickExtension.scala
- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/query/javadsl/JdbcReadJournal.scala
- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- core/src/main/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStore.scala
- core/src/main/scala/akka/persistence/jdbc/util/PluginVersionChecker.scala
- core/src/test/scala/akka/persistence/jdbc/SharedActorSystemTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/SingleActorSystemPerTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/configuration/JNDIConfigTest.scala
- core/src/test/scala/akka/persistence/jdbc/journal/JdbcJournalPerfSpec.scala
- core/src/test/scala/akka/persistence/jdbc/journal/JdbcJournalSpec.scala
- core/src/test/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStoreSpec.scala
Refs #285
Plugin will fail to load if it detects that previous artifact is on the
classpath.
> Previous artifact detection

- src/main/resources/reference.conf
- src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByPersistenceIdTest.scala
- src/test/scala/akka/persistence/jdbc/query/EventsByTagTest.scala
> Backport #329 - eventsByTag fix

- src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- src/main/scala/akka/persistence/jdbc/util/PluginVersionChecker.scala
This is the reverse of #335 for inclusing in 3.5.3.
Refs #338
> Next artifact detection

- docs/src/main/paradox/index.md
> Link to Lightbend's Community Code of Conduct

- docs/src/main/paradox/_template/projectSpecificFooter.st
- docs/src/main/paradox/assets/js/warnOldVersion.js
Add a warning when browsing non-current docs.
> Docs: add version warning support

- project/project-info.conf
> Add supported version

- core/src/main/scala/akka/persistence/jdbc/journal/dao/ByteArrayJournalDao.scala
- core/src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala
References #400 
Change highest sequence number queries to simplify generated sql
> Optimize query of highest seq number

- docs/src/main/paradox/index.md
> Fix link to reference.conf file

- docs/src/main/paradox/index.md
> Links to reference config fixed in index.md

- README.md
References https://github.com/akka/akka-meta/issues/143
> Update to travis-ci.com

- core/src/main/scala/akka/persistence/jdbc/journal/JdbcAsyncWriteJournal.scala
- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
- core/src/main/scala/akka/persistence/jdbc/snapshot/JdbcSnapshotStore.scala
- core/src/test/scala/akka/persistence/jdbc/SharedActorSystemTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/query/JournalDaoStreamMessagesMemoryTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/JournalSequenceActorTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/MultipleReadJournalTest.scala
- core/src/test/scala/akka/persistence/jdbc/query/QueryTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/query/dao/TestProbeReadJournalDao.scala
> Akka 2.6: avoid creating materializers

- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
* probably not important but should be more direct (efficient)
> use Source.futureSource instead of Source.futute.flatMapConcat

- core/src/main/scala/akka/persistence/jdbc/config/AkkaPersistenceConfig.scala
- core/src/main/scala/akka/persistence/jdbc/db/SlickExtension.scala
- core/src/main/scala/akka/persistence/jdbc/util/ConfigOps.scala
- core/src/test/scala/akka/persistence/jdbc/TablesTestSpec.scala
- core/src/test/scala/akka/persistence/jdbc/configuration/AkkaPersistenceConfigTest.scala
- core/src/test/scala/akka/persistence/jdbc/configuration/ConfigOpsTest.scala
Fail if code uses a default value specified in the source code.
All configuration has to be present via config.
References #371
> Read config exclusively from config files

- .scala-steward.conf
References https://github.com/akka/akka-persistence-jdbc/pull/492#issuecomment-765323017
> Don't update Akka via scalasteward

- .github/workflows/check-and-build.yml
- scripts/cat-log.sh
This is a first step PR.
It adds the preliminary checks using GitHub Actions (code format, header, mima, docs). 
Unfortunately, GH Actions don't allow the restart of a single job. We have lots of tests, sometime heavy tests, depending on docker. That means that if a test fail, we have to re-run the whole workflow (all jobs) again.
Therefore, I want to try to use workflow dependency, but first we need to have the main workflow in the master branch. As explained here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
Travis is still enabled and run all tests.
> Run checks with GitHub Actions

- docs/src/main/paradox/migration.md
> Mention change in configuration key for legacy schema

- core/src/main/scala/akka/persistence/jdbc/snapshot/dao/legacy/SnapshotTables.scala
> #521 Allow subtypes of slick.jdbc.OracleProfile to be used

- .github/workflows/release.yml
- project/ProjectAutoPlugin.scala
* sonatypeProfileName "com.lightbend" in projectSettings
* correction of tags
> Fix CI release

- core/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala
> include metadata in EventEnvelope, #532

- core/src/main/scala/akka/persistence/jdbc/state/DurableStateStoreProvider.scala
- core/src/main/scala/akka/persistence/jdbc/testkit/internal/SchemaUtilsImpl.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/DataGenerationHelper.scala
* remove unused method in tests, 
* use Identifier for `JdbcDurableStateStore` 
* remove compilation warning
References https://github.com/akka/akka/issues/30277
> Misc refactoring

- scripts/create-release-issue.sh
Release script now using the official GH client
> update release script

- build.sbt
> let mima use previous stable version

- core/src/main/resources/reference.conf
See https://github.com/akka/akka/issues/31058
> Use default-dispatcher

- .scala-steward.conf
> chore: Don't autoupdate scalafmt

- .github/workflows/h2-test.yml
- .github/workflows/mysql-tests.yml
- .github/workflows/oracle-tests.yml
- .github/workflows/postgres-tests.yml
- .github/workflows/release.yml
- .github/workflows/sqlserver-tests.yml
- core/src/main/scala/akka/persistence/jdbc/state/javadsl/JdbcDurableStateStore.scala
- core/src/main/scala/akka/persistence/jdbc/state/scaladsl/JdbcDurableStateStore.scala
- project/Dependencies.scala
- project/build.properties
* and sbt 1.7.1
* and cleanup of scala versions in ci builds
> Update to Akka 2.7.0-M1

- LICENSE
- project/ProjectAutoPlugin.scala
> chore: License release date for 5.2.1

- .github/workflows/checks.yml
- .github/workflows/h2-test.yml
- .gitignore
- project/Dependencies.scala
See https://github.com/akka/akka/pull/32125
> chore: Drop Scala 2.12

- .github/workflows/h2-test.yml
- .github/workflows/release.yml
- build.sbt
- project/ProjectAutoPlugin.scala
- project/project-info.conf
See https://github.com/akka/akka/pull/32127
> chore: Drop JDK 8

- LICENSE
References https://github.com/akka/akka-persistence-jdbc/issues/814
> chore: License change date for 5.4.0

- .github/workflows/weekly.yml
> build: Conflicting names for IT and weekly IT workflows

- docs/src/main/paradox/migration.md
- docs/src/main/paradox/overview.md
> chore: update migration guide

- LICENSE
References https://github.com/akka/akka-persistence-jdbc/issues/850
> chore: License change date for 5.4.2

- .github/workflows/test.yml
> build: Disable SQL Server integration tests for now

- .github/workflows/test.yml
- core/src/test/resources/sqlserver-application.conf
- core/src/test/resources/sqlserver-shared-db-application.conf
- migrator/src/test/resources/sqlserver-application.conf
- scripts/docker-compose.yml
- scripts/launch-sqlserver.sh
- scripts/sqlserver-cli.sh
> build: Switch docker image for MS Sql Server and re-enable CI job

- docs/src/main/paradox/configuration.md
This provides more details on how to decrease latency - especially for mostly idle systems.
> Add tuning tips

- core/src/main/mima-filters/5.5.0.backwards.excludes/issue-891-durable-store.excludes
- core/src/main/scala/akka/persistence/jdbc/state/JdbcDurableStateStoreProvider.scala
- core/src/main/scala/akka/persistence/jdbc/state/scaladsl/JdbcDurableStateStore.scala
- core/src/test/resources/h2-application.conf
- core/src/test/resources/postgres-shared-db-application.conf
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/DurableStateSequenceActorTest.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/DurableStateStorePluginSpec.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/JdbcDurableStateSpec.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/StateSpecBase.scala
- core/src/test/scala/akka/persistence/jdbc/state/scaladsl/TestProbeDurableStateStoreQuery.scala
> fix: Support more than one JdbcDurableStateStore, #891

- LICENSE
References https://github.com/akka/akka-persistence-jdbc/issues/897
> chore: License change date for 5.5.1

- core/src/main/scala/akka/persistence/jdbc/query/JournalSequenceActor.scala
> backport fix: avoid a range of more than Int.MaxValue elements in JournalSequenceActor

- LICENSE
References https://github.com/akka/akka-persistence-jdbc/issues/911
> chore: License change date for 5.5.2
